#! /bin/sh

set -euo pipefail

files='.config_entries.json .HA_VERSION .ios.conf .uuid automations.yaml
configuration.yaml customize.yaml entity_registry.yaml groups.yaml
input_boolean.yaml input_select.yaml known_devices.yaml nest.conf scenes.yaml
scripts.yaml secrets.yaml zones.yaml'
dirs='custom_components packages'

clean=$(git status -s | wc -l)
if [ $clean -gt 0 ]; then
	echo Repo is not clean
	exit 1
fi

for f in ${files}
do
	scp root@192.168.30.19:/config/$f .
done

for d in ${dirs}
do
    [ -d $d ] || mkdir $d
    scp -pr root@192.168.30.19:/config/${d}/* ${d}/
done
