#! /bin/sh

set -euo pipefail

files='.ios.conf automations.yaml configuration.yaml customize.yaml groups.yaml
input_boolean.yaml input_select.yaml known_devices.yaml scenes.yaml 
scripts.yaml secrets.yaml zones.yaml'

clean=$(git status -s | wc -l)
if [ $clean -gt 0 ]; then
	echo Repo is not clean
	exit 1
fi

for f in ${files}
do
	scp root@hassio.local:/config/$f .
done
scp -pr root@hassio.local:/config/custom_components/* custom_components/
