- id: '1600897077572'
  alias: 'Andrea light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/andrea_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc56076fc1711ea90bd995e3a1400a7
    entity_id: light.andrea
    domain: light
  mode: single
- id: '1600897936269'
  alias: 'Marta light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/marta_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc43964fc1711eab64f3bdc62a4d590
    entity_id: light.marta
    domain: light
  mode: single
- id: '1601215489574'
  alias: 'Bedroom ceiling light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/bedroom_ceiling_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.bedroom_ceiling
  mode: single
- id: '1601240859911'
  alias: 'Kitchen ceiling light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: livingroom/binary_sensor/kitchen_ceiling_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.kitchen_ceiling
  mode: single
- id: '1601240909343'
  alias: 'Living room ceiling light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: livingroom/binary_sensor/living_room_ceiling_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.living_room_ceiling
  mode: single
- id: '1601901374236'
  alias: Marta left the Shrubbery
  description: ''
  trigger:
  - platform: zone
    entity_id: person.marta
    zone: zone.shrubbery
    event: leave
  condition: []
  action:
  - service: notify.mobile_app_andrea
    data:
      message: Marta left the Shrubbery
  mode: single
- id: '1601901840006'
  alias: Marta on the move
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.sm_g973f
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: test
      payload: Marta just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }}
  mode: single
- id: '1602750554947'
  alias: Reminder to cover lamb's lettuce
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: weather.campederiva
    attribute: temperature
    below: '9'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: Cover the lamb's lettuce
  - service: notify.mobile_app_andrea
    data:
      message: Cover lamb's lettuce
  mode: single
- id: '1602750703128'
  alias: Too hot in the fridge
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.fridge_temperature
    below: '10'
    for: 05:00
  condition: []
  action:
  - service: notify.mobile_app_andrea
    data:
      message: Fridge is too warm
  - service: persistent_notification.create
    data:
      message: Fridge is too warm
  mode: single
- id: '1639936637284'
  alias: 'Davide lightstrip: toggle on switch'
  description: ''
  trigger:
  - platform: mqtt
    topic: davide/binary_sensor/lightstrip_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc8a9f4fc1711eab9acc74229a3942c
    entity_id: light.hue_lightstrip_plus_1
    domain: light
  mode: single
- id: '1639936782548'
  alias: 'Davide ceiling: toggle on switch press'
  description: ''
  trigger:
  - platform: mqtt
    topic: davide/binary_sensor/ceiling_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.kids_bedroom_ceiling
  mode: single
