- id: '1600897077572'
  alias: 'Andrea light: turn on when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/andrea_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc56076fc1711ea90bd995e3a1400a7
    entity_id: light.andrea
    domain: light
  mode: single
- id: '1600897936269'
  alias: 'Marta light: turn on when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/marta_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc43964fc1711eab64f3bdc62a4d590
    entity_id: light.marta
    domain: light
  mode: single
- id: '1600898255154'
  alias: 'Andrea switch light: turn off when Andrea light goes off'
  description: ''
  trigger:
  - platform: state
    entity_id: light.andrea
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bedroom/switch/andrea_light/command
      payload: 'OFF'
  mode: single
- id: '1600899972543'
  alias: 'Andrea switch light: turn on when Andrea light goes on'
  description: ''
  trigger:
  - platform: state
    entity_id: light.andrea
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bedroom/switch/andrea_light/command
      payload: 'ON'
  mode: single
- id: '1601021835492'
  alias: 'Marta switch light: turn on when Marta light goes on'
  description: ''
  trigger:
  - platform: state
    entity_id: light.marta
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bedroom/switch/marta_light/command
      payload: 'ON'
  mode: single
- id: '1601021887611'
  alias: 'Marta switch light: turn off when Marta light goes off'
  description: ''
  trigger:
  - platform: state
    entity_id: light.marta
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bedroom/switch/marta_light/command
      payload: 'OFF'
  mode: single
- id: '1601022116689'
  alias: 'Bedroom ceiling switch light: turn on when Bedroom light goes on'
  description: ''
  trigger:
  - platform: state
    entity_id: light.bedroom
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bedroom/switch/bedroom_ceiling/command
      payload: 'ON'
  mode: single
- id: '1601022149132'
  alias: 'Bedroom ceiling switch light: turn off when Bedroom light goes off'
  description: ''
  trigger:
  - platform: state
    entity_id: light.bedroom
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bedroom/switch/bedroom_ceiling/command
      payload: 'OFF'
  mode: single
