- id: '1600897077572'
  alias: 'Andrea light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/andrea_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc56076fc1711ea90bd995e3a1400a7
    entity_id: light.andrea
    domain: light
  mode: single
- id: '1600897936269'
  alias: 'Marta light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/marta_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc43964fc1711eab64f3bdc62a4d590
    entity_id: light.marta
    domain: light
  mode: single
- id: '1601215489574'
  alias: 'Bedroom ceiling light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: bedroom/binary_sensor/bedroom_ceiling_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.bedroom_ceiling
  mode: single
- id: '1601240301803'
  alias: 'Kitchen ceiling light: toggle when switch is pressed'
  description: ''
  trigger:
  - platform: mqtt
    topic: livingroom/binary_sensor/kitchen_touchpad/state
    payload: 'ON'
  condition: []
  action:
  - type: toggle
    device_id: ecc69650fc1711eaa435978d7517c72f
    entity_id: light.kitchen_door
    domain: light
  mode: single
