# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'bedroom'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.30.235:80']

  - job_name: 'greenhouse'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.30.90:80']

    metric_relabel_configs:
      # esphome_sensor_value for Xiaomi Flora sensors
      - source_labels: ["name"]
        regex: '(.*) - (Illuminance|Moisture|Temperature)'
        replacement: '$1'
        target_label: target
      - source_labels: ["name"]
        regex: '(.*) - (Illuminance|Moisture|Temperature)'
        replacement: 'Plant'
        target_label: kind
      - source_labels: ["name"]
        regex: '(.*) - (Illuminance|Moisture|Temperature)'
        replacement: '$2'
        target_label: metric

      # esphome_sensor_value for Xiaomi temperature sensor
      - source_labels: ["name"]
        regex: '(Fridge) (.*)'
        replacement: '$1'
        target_label: target
      - source_labels: ["name"]
        regex: '(Fridge) (.*)'
        replacement: 'Fridge'
        target_label: kind
      - source_labels: ["name"]
        regex: '(Fridge) (.*)'
        replacement: '$2'
        target_label: metric
      - source_labels: ["name"]
        regex: '(Fridge) (.*)'
        replacement: 'Shelf 1 Right'
        target_label: location


  - job_name: 'livingroom'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.30.243:80']

  - job_name: 'homeassistant'
    scrape_interval: 60s
    metrics_path: /api/prometheus

    # Long-Lived Access Token
    bearer_token_file: bearer_token_file

    static_configs:
      - targets: ['192.168.2.2:8123']
