esphome:
  name: bedroom
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret bedroom_ip_address

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

ota:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Activates prometheus /metrics endpoint
prometheus:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Andrea touchpad"
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Marta touchpad"
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Bedroom ceiling touchpad"
    on_press:
      - then:
        - switch.toggle: ceiling_relay
  - platform: status
    name: "Bedroom gang status"

switch:
  # Relay 1-2 unused
  #- platform: gpio
  #  pin: GPIO12
  #- platform: gpio
  #  pin: GPIO5
  - platform: gpio
    id: ceiling_relay
    name: "Bedroom ceiling"
    pin: GPIO4

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Bedroom led"
    output: blue_led
