esphome:
  name: livingroom
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret livingroom_ip_address

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living room Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

ota:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Activates prometheus /metrics endpoint
prometheus:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Living room ceiling touchpad"
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Kitchen ceiling touchpad"
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Kitchen worktop touchpad"
    on_press:
      - then:
        - switch.toggle: kitchen_worktop_relay
  - platform: status
    name: "Living room gang status"

switch:
  - platform: gpio
    pin: GPIO12
    name: "Living room ceiling relay"
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    name: "Kitchen light relay"
    pin: GPIO5
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    id: kitchen_worktop_relay
    name: "Kitchen worktop light relay"
    pin: GPIO4
    restore_mode: RESTORE_DEFAULT_ON

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Living room led"
    output: blue_led
